codecov:
  max_report_age: 24
  require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 0%
        base: auto 