// ENUMS FOR STATUS OF ITEMS
exports.AVAILABLE = "AVAILABLE";
exports.OFFERED = "OFFERED";
exports.SOLD = "SOLD";
exports.RENTED = "RENTED";

// ENUMS FOR TYPE OF TRANSACTION
exports.RENT = "RENT";
exports.SELL = "SELL";
