name: Continuous Integration

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    ### Set the default working directory to be functions

        

### Source: https://github.com/actions/setup-node
    steps:
      - uses: actions/checkout@v3
      - working-directory: ./functions
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
