# Source: https://github.com/actions/setup-node
# Source: https://stackoverflow.com/questions/68527897/how-to-specifiy-path-for-actions-setup-node-in-github
name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  job_1:
    name: Continuous Integration (Testing)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Step 1 -- Clone the repository
        uses: actions/checkout@v3

      - name: Step 2 -- Tell the runner we want to use npm 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Step 3 -- NPM build, install and test
        run: |
          npm ci
          npm run test

      - name: Step 4 -- Upload the test results onto codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true

  job_2:
  # Source: https://github.com/marketplace/actions/github-action-for-firebase
    name: Continuous Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions

    steps:
      - name: Step 1 -- Clone the repository
        uses: actions/checkout@v3

      - name: Step 2 -- Tell the runner we want to use npm 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Step 3 -- NPM build, install and test
        run: |
          npm ci

      - name: Step 4 -- Deploy to Firebase
        uses: "w9jds/firebase-action@master"
        with:
          args: deploy
        env:
    # Obtained from running firebase login:ci
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
