name: Continuous Integration

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    ### Set the default working directory to be functions
    defaults:
      run:
        working-directory: ./functions

        

### Source: https://github.com/actions/setup-node
### Source: https://stackoverflow.com/questions/68527897/how-to-specifiy-path-for-actions-setup-node-in-github
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'
          
      - name: Running npm ci
        run: npm ci
        
      - run: npm run test
