  # Source: https://github.com/actions/setup-node
  # Source: https://stackoverflow.com/questions/68527897/how-to-specifiy-path-for-actions-setup-node-in-github
name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  job_1:
    name: Uploading the code coverage to codecov
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps: 
      - name: Step 1 -- Clone the repository
        uses: actions/checkout@v3

      - name: Step 2 -- Tell the runner we want to use npm 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Step 3 -- Install the relevant node modules
        run: npm ci

      - name: Step 4 -- Run the test and obtain the code coverage
        run: npm run test

      - name: Step 5 -- Upload the test results onto codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true

      - name: Step 6 -- Download the result into an artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-cov
          path: code-cov.txt
